version: '3.8'

services:
  auth:
    image: auth
    ports:
      - "3001:3001"
    deploy:
      replicas: 3 
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
    environment:
      - API_PORT = 3001
      - TOKEN_KEY = 'RAFVI KUAMR EAGADSFAFASF'
      - MONGOOSE_URL = mongodb://localhost:27017
    depends_on:
      - mongo

  search:
    image: search
    ports:
      - "3002:3002"
    deploy:
      replicas: 2 
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3002/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
    environment:
      - API_PORT = 3002
      - MONGOOSE_URL = mongodb+srv://duttatanmoy834:NVFsMuGofmuTugwk@blog.e8i6o.mongodb.net/
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
